Update runOnceDownload.yml

diff --git a/.github/workflows/runOnceDownload.yml b/.github/workflows/runOnceDownload.yml
--- a/.github/workflows/runOnceDownload.yml
+++ b/.github/workflows/runOnceDownload.yml
@@ -47,7 +47,12 @@ jobs:
         run: npm install
 
       - name: Run JS file
-        run: node test.js
+        run: |
+            node test.js
+            if [ $? -ne 0 ]; then
+                echo "Error occurred while running test.js"
+            exit 1
+            fi
         
       - name: Delete files
         run: rm -rf moodleVersions.json ./environment environment.zip
